### PR TITLE
fix: update portrait image handling and refresh logic

### LINKED ISSUE #64: Entity relationships are missing
One example:

```json
  { "021037": "0c3798a7-b6a5-4474-a402-fb0f98bbfa55" }
```

### PR DESCRIPTION
**Pull request by GaryB432**
Fixes #64

### CODE REVIEW

File: libraries/wikibase/src/logic/portrait-thumbnail.ts [hunk 1]
```diff
@@ -19,32 +19,43 @@ export async function refreshPortraitThumbnails(
...
+    });
   }
 }
 
 function inferScheme(source: string): string {
   return source.startsWith("//") ? `https:${source}` : source;
 }
+
+function freshNewPortrait(
+  tn: CommonsPage | undefined,
```
Comment (GaryB432) [inline libraries/wikibase/src/logic/portrait-thumbnail.ts]: use a name reflecting this is a thumbnail page ❓
